/// Flutter icons ButtomBarIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ButtomBarIcons
///      fonts:
///       - asset: fonts/ButtomBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomBarIcons {
  BottomBarIcons._();

  static const _kFontFam = 'ButtomBarIcons';
  static const String? _kFontPkg = null;

  static const IconData shopping_bag_svgrepo_com = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore_tool_svgrepo_com = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
